export const projects = [
  {
    title: 'React Portfolio',
    description: "Using React, Javascript, and CSS including styled-components to build a personal portfolio.",
      image: '/images/portfolio.png',
      tags: ['React.JS', 'Javascript', 'Styled-Components'],
    source: 'https://github.com/kefr1901/portfolio-react',
    visit: 'https://kevinfridman.vercel.app/',
    id: 0,
  },
  {
    title: 'Viseul Group',
    description:"A wordpress-driven website for a electricity company. Responsive and with a nice layout",
    image: '/images/www.visuelgroup.se_.png',
    tags: ['Javascript', 'PHP', 'Wordpress'],
    source: '',
    visit: 'https://www.visuelgroup.se/',
    id: 1,
  },
  {
    title: 'Weather-app',
    description: "React weather application, built with hooks & axios for communication.",
    image: '/images/weather.png',
    tags: ['React', 'Javascript', 'API', 'Axios'],
    source: 'https://github.com/kefr1901/react-api-weather-app',
    visit: 'https://react-api-weather-app.vercel.app/',
    id: 2,
  },
  {
    title: 'Räddningstjänsten Jämntland',
    description: "Participated in the development of the new WCAG accessible website for the Fire Department in Jämtland during my internship.",
      image: '/images/www.rtjamtland.se.png',
      tags: ['Wordpress', 'WCAG', 'Javascript', 'PHP','CSS'],
    source: '',
    visit: 'https://www.rtjamtland.se/',
    id: 3,
  },
  {
    title: 'Honung från Rosenhill',
    description: "A responsive and information-based website for a client who manages and sells organic honey.",
      image: '',
      tags: ['Wordpress', 'Responsive', 'Javascript', 'PHP', 'CSS'],
    source: '',
    visit: '',
    id: 4,
  },
];
